# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ada-cs-namespace
---
# PostgreSQL

# Volúmen persistente
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgres-vol1
  namespace: ada-cs-namespace
spec:
  storageClassName: postgres
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgres-vol1"
---
# Reclamo PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: ada-cs-namespace
spec:
  storageClassName: postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres
  namespace: ada-cs-namespace
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: ada-cs-namespace
data:
  postgres.user: postgres
  postgres.password: password
  postgres.db: postgresdb
---
# Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ada-cs-namespace
  labels:
    app: postgres-server
spec:
  selector:
    matchLabels:
      app: postgres-server
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-server
    spec:
      containers:
      - image: postgres:11
        name: postgres-db1
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-db-volume1
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: postgres.user
          - name: POSTGRES_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: postgres.password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres
                key: postgres.db
      volumes:
      - name: postgres-db-volume1
        persistentVolumeClaim:
           claimName: pvc-postgres
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: ada-cs-namespace
spec:
  selector:
    app: postgres-server
  ports:
    - port: 5300
      targetPort: 5432
  type: LoadBalancer
  ---
 # Redis
# Volúmen persistente
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-redis-vol1
  namespace: ada-cs-namespace
spec:
  storageClassName: redis
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/redis-vol1"
---
# Reclamo PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-redis
  namespace: ada-cs-namespace
  labels:
    app: redis-server
spec:
  storageClassName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: redis
  namespace: ada-cs-namespace
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# ConfigMap
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: redis 
  namespace: ada-cs-namespace
  labels:
    app: redis-server
data:
  redis.password: "password"
  redis.db: "redisdb"
---
# Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: ada-cs-namespace
  labels:
    app: redis-server
spec:
  selector:
    matchLabels:
      app: redis-server
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
    spec:
      containers:
      - image: redis:latest
        name: redis-db1
        ports:
        - containerPort: 6379
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: redis-db-volume1
        env:
          - name: REDIS_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: redis
                key: redis.password   
          - name: REDIS_DB
            valueFrom:
              configMapKeyRef:
                name: redis
                key: redis.db
      volumes:
      - name: redis-db-volume1
        persistentVolumeClaim:
           claimName: pvc-redis
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: ada-cs-namespace
  labels:
    app: redis-server
spec:
  selector:
    app: redis-server
  ports:  
    - port: 5301
      targetPort: 6379
      protocol: TCP
  type: LoadBalancer
---
# MongoDB

# Volúmen persistente
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-vol1
  namespace: ada-cs-namespace
spec:
  storageClassName: mongo
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo-vol1"
---
# Reclamo PV
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mongo
  namespace: ada-cs-namespace
  labels:
    app: mongo-server
spec:
  storageClassName: mongo
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# StorageClass
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo
  namespace: ada-cs-namespace
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
# ConfigMap
apiVersion: v1 
kind: ConfigMap
metadata:
  name: mongo 
  namespace: ada-cs-namespace
  labels:
    app: mongo-server
data:
  mongo.user: "mongo"
  mongo.password: "password"
  mongo.db: "mongodb"
---
# Deploy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  namespace: ada-cs-namespace
  labels:
    app: mongo-server
spec:
  selector:
    matchLabels:
      app: mongo-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-server
    spec:
      containers:
      - image: mongo:4.1.7
        name: mongo-db1
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: mongo-db-volume1
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: mongo
                key: mongo.user
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mongo
                key: mongo.password
          - name: MONGO_INITDB_ROOT_DB
            valueFrom:
              configMapKeyRef:
                name: mongo
                key: mongo.db
      volumes:
      - name: mongo-db-volume1
        persistentVolumeClaim:
           claimName: pvc-mongo
---
# Service
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: ada-cs-namespace
  labels:
    app: mongo-server
spec:
  selector:
    app: mongo-server
  ports:  
    - port: 5302
      targetPort: 27017
      protocol: TCP
  type: LoadBalancer
---